# Site settings
title: xiaobai1315
description: > # this means to ignore newlines until "baseurl:"
  A super simple white label website built with Jekyll and using Dan Eden's Toast grid layout.
baseurl: ""
url: "https://xiaobai1315.github.io/"
repository: xiaobai1315.github.io
theme-path: theme-assets # path to header assets etc
map-api-key: AIzaSyB3U7uwIvCyq01orxppAIC1v73y-FBGygY
sass:
  sass_dir: _sass
  style: compressed

collections:
  case:
    output: true
    permalink: /case-studies/:path/
  resource:
    output: true
    permalink: /resources/:path/

# Build settings
markdown: kramdown
